version: 2.1

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:25.0.1'
    steps:
      - checkout
      - git-shallow-clone/checkout_advanced:
          clone_options: '--filter=blob:none'
      - run:
          name: "Git fetch"
          command: git fetch --no-filter --refetch
      - run:
          name: Analyze on SonarCloud
          command: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests -Dquarkus.container-image.build=false
  build:
    executor:
      name: docker/machine
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/install_docker_compose
      - maven/with_cache:
          steps:
            - run:
                name: Build Images
                command: mvn package -DskipTests -Dquarkus.container-image.build=true
      - run:
          name: Run Pact Broker
          command: docker-compose up -d
      - maven/with_cache:
          steps:
            - run:
                name: Run Tests
                command: mvn package pact:publish -Dquarkus.container-image.build=false

executors:
  machine:
    machine:
      image: ubuntu-2204:current
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  maven: circleci/maven@2.1.1
  docker: circleci/docker@3.0.1
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0

workflows:
  maven_test:
    jobs:
      - build
      - analyze:
          context: SonarCloud
